server:
  port: 8080

##测试库
spring:
  datasource:
    url: jdbc:mysql://www.zhangchuany.com:3306/testdb?useUnicode=true&characterEncoding=utf-8
    username: ben622
    password:
    driver-class-name: com.mysql.jdbc.Driver
